import type { Metadata } from "next";
import { Oxygen } from "next/font/google";
import Providers from "./providers";

import "react-toastify/dist/ReactToastify.css";
import "./globals.css";

const oxygen = Oxygen({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={oxygen.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
